version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: medflow-mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: medflow
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
